defmodule TrafficLight.Factory do
  @moduledoc false

  def build(:github_payload, %{event: "check_run", status: status}) do
    Poison.decode!(~s(
        {
          "action": "created",
          "check_run": {
            "id": 1134444775,
            "node_id": "MDg6Q2hlY2tSdW4xMTM0NDQ0Nzc1",
            "head_sha": "56ab8ff3460fdefbee3a63ed0eb7aa0b3263eea7",
            "external_id": "ca395085-040a-526b-2ce8-bdc85f692774",
            "url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/check-runs/1134444775",
            "html_url": "https://github.com/fabrik42/traffic-light-server-elixir/runs/1134444775",
            "details_url": "https://github.com/fabrik42/traffic-light-server-elixir/runs/1134444775",
            "status": "#{status}",
            "conclusion": null,
            "started_at": "2020-09-18T14:55:03Z",
            "completed_at": null,
            "output": {
              "title": null,
              "summary": null,
              "text": null,
              "annotations_count": 0,
              "annotations_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/check-runs/1134444775/annotations"
            },
            "name": "build",
            "check_suite": {
              "id": 1212773683,
              "node_id": "MDEwOkNoZWNrU3VpdGUxMjEyNzczNjgz",
              "head_branch": "fabrik42-patch-1",
              "head_sha": "56ab8ff3460fdefbee3a63ed0eb7aa0b3263eea7",
              "status": "queued",
              "conclusion": null,
              "url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/check-suites/1212773683",
              "before": "370c98109a22b4a81fbf27032f813bc1fcc0ffe6",
              "after": "56ab8ff3460fdefbee3a63ed0eb7aa0b3263eea7",
              "pull_requests": [
                {
                  "url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/pulls/3",
                  "id": 489358535,
                  "number": 3,
                  "head": {
                    "ref": "fabrik42-patch-1",
                    "sha": "56ab8ff3460fdefbee3a63ed0eb7aa0b3263eea7",
                    "repo": {
                      "id": 260757715,
                      "url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir",
                      "name": "traffic-light-server-elixir"
                    }
                  },
                  "base": {
                    "ref": "master",
                    "sha": "d9b73f17ee95f71c2dae036c1dbe76b80978093e",
                    "repo": {
                      "id": 260757715,
                      "url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir",
                      "name": "traffic-light-server-elixir"
                    }
                  }
                }
              ],
              "app": {
                "id": 15368,
                "slug": "github-actions",
                "node_id": "MDM6QXBwMTUzNjg=",
                "owner": {
                  "login": "github",
                  "id": 9919,
                  "node_id": "MDEyOk9yZ2FuaXphdGlvbjk5MTk=",
                  "avatar_url": "https://avatars1.githubusercontent.com/u/9919?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/github",
                  "html_url": "https://github.com/github",
                  "followers_url": "https://api.github.com/users/github/followers",
                  "following_url": "https://api.github.com/users/github/following{/other_user}",
                  "gists_url": "https://api.github.com/users/github/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/github/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/github/subscriptions",
                  "organizations_url": "https://api.github.com/users/github/orgs",
                  "repos_url": "https://api.github.com/users/github/repos",
                  "events_url": "https://api.github.com/users/github/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/github/received_events",
                  "type": "Organization",
                  "site_admin": false
                },
                "name": "GitHub Actions",
                "description": "Automate your workflow from idea to production",
                "external_url": "https://help.github.com/en/actions",
                "html_url": "https://github.com/apps/github-actions",
                "created_at": "2018-07-30T09:30:17Z",
                "updated_at": "2019-12-10T19:04:12Z",
                "permissions": {
                  "actions": "write",
                  "checks": "write",
                  "contents": "write",
                  "deployments": "write",
                  "issues": "write",
                  "metadata": "read",
                  "packages": "write",
                  "pages": "write",
                  "pull_requests": "write",
                  "repository_hooks": "write",
                  "repository_projects": "write",
                  "security_events": "write",
                  "statuses": "write",
                  "vulnerability_alerts": "read"
                },
                "events": [
                  "check_run",
                  "check_suite",
                  "create",
                  "delete",
                  "deployment",
                  "deployment_status",
                  "fork",
                  "gollum",
                  "issues",
                  "issue_comment",
                  "label",
                  "milestone",
                  "page_build",
                  "project",
                  "project_card",
                  "project_column",
                  "public",
                  "pull_request",
                  "pull_request_review",
                  "pull_request_review_comment",
                  "push",
                  "registry_package",
                  "release",
                  "repository",
                  "repository_dispatch",
                  "status",
                  "watch",
                  "workflow_dispatch",
                  "workflow_run"
                ]
              },
              "created_at": "2020-09-18T14:55:00Z",
              "updated_at": "2020-09-18T14:55:00Z"
            },
            "app": {
              "id": 15368,
              "slug": "github-actions",
              "node_id": "MDM6QXBwMTUzNjg=",
              "owner": {
                "login": "github",
                "id": 9919,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjk5MTk=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/9919?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/github",
                "html_url": "https://github.com/github",
                "followers_url": "https://api.github.com/users/github/followers",
                "following_url": "https://api.github.com/users/github/following{/other_user}",
                "gists_url": "https://api.github.com/users/github/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/github/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/github/subscriptions",
                "organizations_url": "https://api.github.com/users/github/orgs",
                "repos_url": "https://api.github.com/users/github/repos",
                "events_url": "https://api.github.com/users/github/events{/privacy}",
                "received_events_url": "https://api.github.com/users/github/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "name": "GitHub Actions",
              "description": "Automate your workflow from idea to production",
              "external_url": "https://help.github.com/en/actions",
              "html_url": "https://github.com/apps/github-actions",
              "created_at": "2018-07-30T09:30:17Z",
              "updated_at": "2019-12-10T19:04:12Z",
              "permissions": {
                "actions": "write",
                "checks": "write",
                "contents": "write",
                "deployments": "write",
                "issues": "write",
                "metadata": "read",
                "packages": "write",
                "pages": "write",
                "pull_requests": "write",
                "repository_hooks": "write",
                "repository_projects": "write",
                "security_events": "write",
                "statuses": "write",
                "vulnerability_alerts": "read"
              },
              "events": [
                "check_run",
                "check_suite",
                "create",
                "delete",
                "deployment",
                "deployment_status",
                "fork",
                "gollum",
                "issues",
                "issue_comment",
                "label",
                "milestone",
                "page_build",
                "project",
                "project_card",
                "project_column",
                "public",
                "pull_request",
                "pull_request_review",
                "pull_request_review_comment",
                "push",
                "registry_package",
                "release",
                "repository",
                "repository_dispatch",
                "status",
                "watch",
                "workflow_dispatch",
                "workflow_run"
              ]
            },
            "pull_requests": [
              {
                "url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/pulls/3",
                "id": 489358535,
                "number": 3,
                "head": {
                  "ref": "fabrik42-patch-1",
                  "sha": "56ab8ff3460fdefbee3a63ed0eb7aa0b3263eea7",
                  "repo": {
                    "id": 260757715,
                    "url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir",
                    "name": "traffic-light-server-elixir"
                  }
                },
                "base": {
                  "ref": "master",
                  "sha": "d9b73f17ee95f71c2dae036c1dbe76b80978093e",
                  "repo": {
                    "id": 260757715,
                    "url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir",
                    "name": "traffic-light-server-elixir"
                  }
                }
              }
            ]
          },
          "repository": {
            "id": 260757715,
            "node_id": "MDEwOlJlcG9zaXRvcnkyNjA3NTc3MTU=",
            "name": "traffic-light-server-elixir",
            "full_name": "fabrik42/traffic-light-server-elixir",
            "private": false,
            "owner": {
              "login": "fabrik42",
              "id": 223822,
              "node_id": "MDQ6VXNlcjIyMzgyMg==",
              "avatar_url": "https://avatars3.githubusercontent.com/u/223822?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/fabrik42",
              "html_url": "https://github.com/fabrik42",
              "followers_url": "https://api.github.com/users/fabrik42/followers",
              "following_url": "https://api.github.com/users/fabrik42/following{/other_user}",
              "gists_url": "https://api.github.com/users/fabrik42/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/fabrik42/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/fabrik42/subscriptions",
              "organizations_url": "https://api.github.com/users/fabrik42/orgs",
              "repos_url": "https://api.github.com/users/fabrik42/repos",
              "events_url": "https://api.github.com/users/fabrik42/events{/privacy}",
              "received_events_url": "https://api.github.com/users/fabrik42/received_events",
              "type": "User",
              "site_admin": false
            },
            "html_url": "https://github.com/fabrik42/traffic-light-server-elixir",
            "description": "Configure traffic lights on Heroku, powered by Elixir and Phoenix",
            "fork": false,
            "url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir",
            "forks_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/forks",
            "keys_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/teams",
            "hooks_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/hooks",
            "issue_events_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/issues/events{/number}",
            "events_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/events",
            "assignees_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/assignees{/user}",
            "branches_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/branches{/branch}",
            "tags_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/tags",
            "blobs_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/languages",
            "stargazers_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/stargazers",
            "contributors_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/contributors",
            "subscribers_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/subscribers",
            "subscription_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/subscription",
            "commits_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/contents/{+path}",
            "compare_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/merges",
            "archive_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/downloads",
            "issues_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/issues{/number}",
            "pulls_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/labels{/name}",
            "releases_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/releases{/id}",
            "deployments_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/deployments",
            "created_at": "2020-05-02T19:14:01Z",
            "updated_at": "2020-09-18T14:25:38Z",
            "pushed_at": "2020-09-18T14:54:57Z",
            "git_url": "git://github.com/fabrik42/traffic-light-server-elixir.git",
            "ssh_url": "git@github.com:fabrik42/traffic-light-server-elixir.git",
            "clone_url": "https://github.com/fabrik42/traffic-light-server-elixir.git",
            "svn_url": "https://github.com/fabrik42/traffic-light-server-elixir",
            "homepage": "",
            "size": 10950,
            "stargazers_count": 3,
            "watchers_count": 3,
            "language": "Elixir",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "forks_count": 1,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 1,
            "license": null,
            "forks": 1,
            "open_issues": 1,
            "watchers": 3,
            "default_branch": "master"
          },
          "sender": {
            "login": "fabrik42",
            "id": 223822,
            "node_id": "MDQ6VXNlcjIyMzgyMg==",
            "avatar_url": "https://avatars3.githubusercontent.com/u/223822?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabrik42",
            "html_url": "https://github.com/fabrik42",
            "followers_url": "https://api.github.com/users/fabrik42/followers",
            "following_url": "https://api.github.com/users/fabrik42/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabrik42/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabrik42/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabrik42/subscriptions",
            "organizations_url": "https://api.github.com/users/fabrik42/orgs",
            "repos_url": "https://api.github.com/users/fabrik42/repos",
            "events_url": "https://api.github.com/users/fabrik42/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabrik42/received_events",
            "type": "User",
            "site_admin": false
          }
        }
        ))
  end

  def build(:github_payload, %{event: "check_suite", status: status}) do
    Poison.decode!(~s(
        {
          "action": "completed",
          "check_suite": {
            "id": 1212773683,
            "node_id": "MDEwOkNoZWNrU3VpdGUxMjEyNzczNjgz",
            "head_branch": "fabrik42-patch-1",
            "head_sha": "56ab8ff3460fdefbee3a63ed0eb7aa0b3263eea7",
            "status": "completed",
            "conclusion": "#{status}",
            "url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/check-suites/1212773683",
            "before": "370c98109a22b4a81fbf27032f813bc1fcc0ffe6",
            "after": "56ab8ff3460fdefbee3a63ed0eb7aa0b3263eea7",
            "pull_requests": [
              {
                "url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/pulls/3",
                "id": 489358535,
                "number": 3,
                "head": {
                  "ref": "fabrik42-patch-1",
                  "sha": "56ab8ff3460fdefbee3a63ed0eb7aa0b3263eea7",
                  "repo": {
                    "id": 260757715,
                    "url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir",
                    "name": "traffic-light-server-elixir"
                  }
                },
                "base": {
                  "ref": "master",
                  "sha": "d9b73f17ee95f71c2dae036c1dbe76b80978093e",
                  "repo": {
                    "id": 260757715,
                    "url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir",
                    "name": "traffic-light-server-elixir"
                  }
                }
              }
            ],
            "app": {
              "id": 15368,
              "slug": "github-actions",
              "node_id": "MDM6QXBwMTUzNjg=",
              "owner": {
                "login": "github",
                "id": 9919,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjk5MTk=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/9919?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/github",
                "html_url": "https://github.com/github",
                "followers_url": "https://api.github.com/users/github/followers",
                "following_url": "https://api.github.com/users/github/following{/other_user}",
                "gists_url": "https://api.github.com/users/github/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/github/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/github/subscriptions",
                "organizations_url": "https://api.github.com/users/github/orgs",
                "repos_url": "https://api.github.com/users/github/repos",
                "events_url": "https://api.github.com/users/github/events{/privacy}",
                "received_events_url": "https://api.github.com/users/github/received_events",
                "type": "Organization",
                "site_admin": false
              },
              "name": "GitHub Actions",
              "description": "Automate your workflow from idea to production",
              "external_url": "https://help.github.com/en/actions",
              "html_url": "https://github.com/apps/github-actions",
              "created_at": "2018-07-30T09:30:17Z",
              "updated_at": "2019-12-10T19:04:12Z",
              "permissions": {
                "actions": "write",
                "checks": "write",
                "contents": "write",
                "deployments": "write",
                "issues": "write",
                "metadata": "read",
                "packages": "write",
                "pages": "write",
                "pull_requests": "write",
                "repository_hooks": "write",
                "repository_projects": "write",
                "security_events": "write",
                "statuses": "write",
                "vulnerability_alerts": "read"
              },
              "events": [
                "check_run",
                "check_suite",
                "create",
                "delete",
                "deployment",
                "deployment_status",
                "fork",
                "gollum",
                "issues",
                "issue_comment",
                "label",
                "milestone",
                "page_build",
                "project",
                "project_card",
                "project_column",
                "public",
                "pull_request",
                "pull_request_review",
                "pull_request_review_comment",
                "push",
                "registry_package",
                "release",
                "repository",
                "repository_dispatch",
                "status",
                "watch",
                "workflow_dispatch",
                "workflow_run"
              ]
            },
            "created_at": "2020-09-18T14:55:00Z",
            "updated_at": "2020-09-18T14:57:04Z",
            "latest_check_runs_count": 1,
            "check_runs_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/check-suites/1212773683/check-runs",
            "head_commit": {
              "id": "56ab8ff3460fdefbee3a63ed0eb7aa0b3263eea7",
              "tree_id": "8379993926f11598d60dd4419bb2c9869d6ebd1c",
              "message": "Update README.org",
              "timestamp": "2020-09-18T14:54:56Z",
              "author": {
                "name": "Christian Bäuerlein",
                "email": "hello@christianbaeuerlein.com"
              },
              "committer": {
                "name": "GitHub",
                "email": "noreply@github.com"
              }
            }
          },
          "repository": {
            "id": 260757715,
            "node_id": "MDEwOlJlcG9zaXRvcnkyNjA3NTc3MTU=",
            "name": "traffic-light-server-elixir",
            "full_name": "fabrik42/traffic-light-server-elixir",
            "private": false,
            "owner": {
              "login": "fabrik42",
              "id": 223822,
              "node_id": "MDQ6VXNlcjIyMzgyMg==",
              "avatar_url": "https://avatars3.githubusercontent.com/u/223822?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/fabrik42",
              "html_url": "https://github.com/fabrik42",
              "followers_url": "https://api.github.com/users/fabrik42/followers",
              "following_url": "https://api.github.com/users/fabrik42/following{/other_user}",
              "gists_url": "https://api.github.com/users/fabrik42/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/fabrik42/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/fabrik42/subscriptions",
              "organizations_url": "https://api.github.com/users/fabrik42/orgs",
              "repos_url": "https://api.github.com/users/fabrik42/repos",
              "events_url": "https://api.github.com/users/fabrik42/events{/privacy}",
              "received_events_url": "https://api.github.com/users/fabrik42/received_events",
              "type": "User",
              "site_admin": false
            },
            "html_url": "https://github.com/fabrik42/traffic-light-server-elixir",
            "description": "Configure traffic lights on Heroku, powered by Elixir and Phoenix",
            "fork": false,
            "url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir",
            "forks_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/forks",
            "keys_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/teams",
            "hooks_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/hooks",
            "issue_events_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/issues/events{/number}",
            "events_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/events",
            "assignees_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/assignees{/user}",
            "branches_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/branches{/branch}",
            "tags_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/tags",
            "blobs_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/languages",
            "stargazers_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/stargazers",
            "contributors_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/contributors",
            "subscribers_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/subscribers",
            "subscription_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/subscription",
            "commits_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/contents/{+path}",
            "compare_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/merges",
            "archive_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/downloads",
            "issues_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/issues{/number}",
            "pulls_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/labels{/name}",
            "releases_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/releases{/id}",
            "deployments_url": "https://api.github.com/repos/fabrik42/traffic-light-server-elixir/deployments",
            "created_at": "2020-05-02T19:14:01Z",
            "updated_at": "2020-09-18T14:25:38Z",
            "pushed_at": "2020-09-18T14:54:57Z",
            "git_url": "git://github.com/fabrik42/traffic-light-server-elixir.git",
            "ssh_url": "git@github.com:fabrik42/traffic-light-server-elixir.git",
            "clone_url": "https://github.com/fabrik42/traffic-light-server-elixir.git",
            "svn_url": "https://github.com/fabrik42/traffic-light-server-elixir",
            "homepage": "",
            "size": 10950,
            "stargazers_count": 3,
            "watchers_count": 3,
            "language": "Elixir",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "forks_count": 1,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 1,
            "license": null,
            "forks": 1,
            "open_issues": 1,
            "watchers": 3,
            "default_branch": "master"
          },
          "sender": {
            "login": "fabrik42",
            "id": 223822,
            "node_id": "MDQ6VXNlcjIyMzgyMg==",
            "avatar_url": "https://avatars3.githubusercontent.com/u/223822?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fabrik42",
            "html_url": "https://github.com/fabrik42",
            "followers_url": "https://api.github.com/users/fabrik42/followers",
            "following_url": "https://api.github.com/users/fabrik42/following{/other_user}",
            "gists_url": "https://api.github.com/users/fabrik42/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fabrik42/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fabrik42/subscriptions",
            "organizations_url": "https://api.github.com/users/fabrik42/orgs",
            "repos_url": "https://api.github.com/users/fabrik42/repos",
            "events_url": "https://api.github.com/users/fabrik42/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fabrik42/received_events",
            "type": "User",
            "site_admin": false
          }
        }
        ))
  end

  # Payload taken from https://documentation.codeship.com/general/projects/notifications/
  def build(:codeship_payload, %{status: status}) do
    Poison.decode!(~s(
          {
            "build": {
              "build_url":"https://www.codeship.com/projects/10213/builds/973711",
              "commit_url":"https://github.com/codeship/docs/
              commit/96943dc5269634c211b6fbb18896ecdcbd40a047",
              "project_id":10213,
              "build_id":973711,
              "status":"#{status}",
              "project_full_name":"codeship/docs",
              "project_name":"codeship/docs",
              "commit_id":"96943dc5269634c211b6fbb18896ecdcbd40a047",
              "short_commit_id":"96943",
              "message":"Merge pull request #34 from codeship/feature/shallow-clone",
              "committer":"beanieboi",
              "branch":"master"
            }
          }
        ))
  end
end
